scorbot:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    base_position_controller:
        type: effort_controllers/JointPositionController
        joint: base_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}
    shoulder_position_controller:
        type: effort_controllers/JointPositionController
        joint: shoulder_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}
    elbow_position_controller:
        type: effort_controllers/JointPositionController
        joint: elbow_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}
    wrist_pitch_position_controller:
        type: effort_controllers/JointPositionController
        joint: pitch_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}
    wrist_roll_position_controller:
        type: effort_controllers/JointPositionController
        joint: roll_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}
    lpad_position_controller:
        type: effort_controllers/JointPositionController
        joint: lpad_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}
    rpad_position_controller:
        type: effort_controllers/JointPositionController
        joint: rpad_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}

